config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about" , as: "about"
  resources :books, only: [:new, :create, :edit, :update, :index, :show,  :destroy]
  resources :users, only: [:new, :show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  has_one_attached :image
  has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  has_one_attached :profile_image

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render:index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render:edit
    else
      redirect_to '/books'
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render:edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
   @users = User.all
   @user = User.find(current_user.id)
   @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render:edit
    else
      redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
     if  @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
     else
      render :edit
     end
  end

   private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
  <h2>User info</h2>
  <table class="table">
  <tbody>
  <%= image_tag user.get_profile_image(100,100) %>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
  </table>
   <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <h2>New book</h2>
  <%= form_with model: book do |f| %>
  <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
     <br>
       <%= f.submit 'Create Book' ,class: "btn btn-success" %>
     </br>
    <% end %>
  </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
       <%= form_with model: @book do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <br> <%= f.submit 'Update Book' ,class: "btn btn-success" %></br>
       <% end %>
      <br> <%=link_to "Show" , book_path(@book.id) %>
       <%= link_to "Back" , "/books" %></br>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
<%= render 'list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do | book | %>
      <tr>
        <td><%= link_to user_path(book.user_id) do%>
        <%= image_tag book.user.get_profile_image(80,80) %>
        <% end %>
        <td><%= link_to book.title , book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
  <%= form_with model: @book, url: '/books', method: :post do |f| %>do |f| %>
  <h4>Title</h4>
      <%= f.text_field :book_title %>
    <h4>Opinion</h4>
      <%= f.text_area :caption %>
    <%= f.submit 'create' %>
  <% end %>

app/views/books/show.html.erb
<%= render 'list', book: @book_new, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table table-hover table-inverse">
   <tbody>
    <tr>
     <td><%= link_to user_path(@user.id) do%>
        <%= image_tag @book.user.get_profile_image(80,80) %>
        <% end %>
     <br><%= link_to @book.user.name, user_path(@user.id) %></br></td>
     <td><%= @book.title %></td>
     <td><%= @book.body %></td>
      <% if @book.user == current_user %>
     <td> <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
     <td> <%= link_to "Destroy", book_path(@book), method: :delete ,"data-confirm" => "本当に削除しますか？" , class: "btn btn-danger"%></td>
      <% end %>
     </tr>
    </tbody>
    </table>
</div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
   <%= notice %>
   <%= alert %>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

   <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to user_path(current_user.id) ,class: 'nav-link text-light' do %>
      <i class="fas fa-home"></i>
       Homes
      <% end %>
      <li class="nav-item">
      <%= link_to "/users",class: 'nav-link text-light' do %>
      <i class="fas fa-users"></i>
       Users
      <% end %>
       <li class="nav-item">
      <%= link_to "/books" ,class: 'nav-link text-light' do %>
      <i class="fas fa-book-open"></i>
       Books
      <% end %>
    <li class="nav-item">
       <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
      <i class="fas fa-sign-out-alt"></i>
      Log out
      <% end %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "/" ,class: 'nav-link text-light' do %>
      <i class="fas fa-home"></i>
       Homes
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to "/home/about" ,class: 'nav-link text-light' do %>
      <i class="fas fa-link"></i>
      About
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
       <i class="fas fa-user-plus"></i>
        Sign up
       <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
        <i class="fas fa-sign-in-alt"></i>
        Log in
      <% end %>
    </li>
    <% end %>
    </ul>
    </div>
    </div>
   </nav>
  </header>
    <%= yield %>
 
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %> error prohibited this obj from being saved:
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>
<br> <label for="inputName">Name</label></br>
<br> <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></br>
<br> <label for="inputImage">Image</label></br>
<br><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></br>
<br><label for="user_introduction">Introduction</label></br>
<br><%= f.text_area :introduction %></br>
<br><%= f.submit "Update User", class:  "btn btn-secondary" %></br>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'books/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>Name</th>
      <th colspan ="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
       <td><%= image_tag user.get_profile_image(80,80) %></td>
       <td><%= user.name %></td>
       <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do | book | %>
      <tr>
        <td><%= link_to user_path(book.user_id) do%>
        <%= image_tag book.user.get_profile_image(80,80) %>
        <% end %>
        <td><%= link_to book.title , book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>